### ISSUE TITLE
A task is missing The pipeline references a task called 'AzureImageBuilderTask'

### ISSUE THREAD

**Issue by dtvn-duytq7** [Azure/azvmimagebuilder#58]
My pipelines (YAML based) failed to build when I using a task `AzureImageBuilderTask@1` or `AzureImageBuilder.devOps-task-for-azure-image-builder.custom-build-release-task.AzureImageBuilderTask@1`.

**
A task is missing. The pipeline references a task called ‘AzureImageBuilderTask’. This usually indicates the task isn’t installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com/. (Task version 1, job ‘Upload’, step ‘’.)
**

I didn’t see any issues in Dev community already.

Kindly can someone validate and let me know the potential cause for the problem and provide the fix.

- My pipiline:
```
    - task: AzureImageBuilder.devOps-task-for-azure-image-builder.custom-build-release-task.AzureImageBuilderTask@1
      displayName: 'Azure VM Image Builder Task'
      inputs:
        managedIdentity: '/subscriptions/$(SUBSCRIPTION_ID)/resourcegroups/$(RESOURCE_GROUP)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$(IDENTITY_NAME)'
        imageSource: marketplace
        windowsUpdateProvisioner: true
        packagePath: '$(System.ArtifactsDirectory)/dist'
        storageAccountName: $(STORAGE_ACCOUNT_NAME)
        distributeType: sig
        galleryImageId: '/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(RESOURCE_GROUP)/providers/Microsoft.Compute/galleries/ABC/images/MyImage/versions/0.0.$(Build.BuildId)'
        replicationRegions: 'westeurope'
        ibSubscription: $(SUBSCRIPTION_ID)
        ibAzureResourceGroup: $(RESOURCE_GROUP)
        ibLocation: 'westeurope'
```
